ibm_cloud_networking_services/direct_link_apis_v1.py
test/unit/test_direct_link_apis_v1.py

Refresh the SDK using update spec for DirectLink

feat: refresh SDK to include latest spec changes

---

ibm_cloud_networking_services/version.py
test/integration/test_direct_link_v1.py
test/integration/test_transit_gateway_apis_v1.py

chore: updated the versioning

---

.travis.yml

chore: disable integration tests

---

.travis.yml

fix: run integration tests on Python 3.5

---

ibm_cloud_networking_services/direct_link_v1.py
test/integration/test_direct_link_v1.py
test/unit/test_direct_link_v1.py

added the support for macsec enabled gateway for direct link

feat: added the support for macsec enabled gateway for direct link

---

DEPRECATION-NOTICE.md
README.md
ibm_cloud_networking_services/__init__.py
ibm_cloud_networking_services/dns_global_load_balancers_v1.py
ibm_cloud_networking_services/dns_permitted_networks_v1.py
ibm_cloud_networking_services/dns_resource_records_v1.py
test/integration/test_dns_global_load_balancers_v1.py
test/integration/test_dns_permitted_networks_v1.py
test/integration/test_dns_resource_records_v1.py
test/unit/test_dns_global_load_balancers_v1.py
test/unit/test_dns_permitted_networks_v1.py
test/unit/test_dns_resource_records_v1.py

PDNS - Added renamed-sdk and deprecation notice

---

test/integration/test_direct_link_provider_v2.py
test/integration/test_direct_link_v1.py

chore: fixed integration tests for dl provider and dl

---

.github/workflows/codeql-analysis.yml

Set CodeQL scanning to run weekly in addition to on code checkins

chore: weekly static analysis cron job

---

ibm_cloud_networking_services/__init__.py
ibm_cloud_networking_services/filters_v1.py
test/integration/test_filters_v1.py
test/unit/test_filters_v1.py

feat(filters): added filters

---

ibm_cloud_networking_services/__init__.py
ibm_cloud_networking_services/firewall_rules_v1.py
test/integration/test_firewall_rules_v1.py
test/unit/test_firewall_rules_v1.py

feat(firewall rules):Add Firewall Rules SDK

---

.secrets.baseline

chore: updated .secrets.baseline

---

README.md
requirements-dev.txt
tox.ini

The Python SDK needed to be updated per latest updates in sdk-core templates.
**Fixes:** https://github.ibm.com/CloudEngineering/python-sdk-template/pull/62
Totally functional.
Totally functional.
This PR removes the "codecov" tool from the project.

fix: Updated Python SDK per latest updates in sdk-core templates.

---

package-lock.json

Addresses Security vulnerability 
`Packing does not respect root-level ignore files in workspaces`
**Fixes:** https://github.com/IBM/networking-python-sdk/security/dependabot/11

fix: Fixing Packing does not respect root-level ignore files in workspace issue

---

dl.env.properties
ibm_cloud_networking_services/direct_link_v1.py
test/integration/test_direct_link_v1.py
test/unit/test_direct_link_v1.py

Added Gateway AS Prepends endpoints to SDK,
- List AS prepends
- Replace existing AS prepends
**Fixes:** 

feat (as_prepends): added gateway-as-prepends to direct-link

---

dl.env.properties

Reverts IBM/networking-python-sdk#70

Revert "feat : added AS_Prepends to direct link"

---

dl.env.properties

Reverts IBM/networking-python-sdk#69

Revert "feat: AS-Prepends added to direct link"

---

dl.env.properties

Added AS-Prepends  to direct link https://github.com/IBM/networking-python-sdk/pull/68

feat: added AS-Prepends

---

package-lock.json

fix: updating dependency versions

---

.travis.yml

feat: added DL BGP Route filtering

---

.github/workflows/codeql-analysis.yml

Link: https://github.com/IBM/networking-python-sdk/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BNMFXGC3DZONUXGLTZNVWA 
https://github.com/IBM/networking-python-sdk/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BNMFXGC3DZONUXGLTZNVWA/5b869ea5aa9e968c88615657bae5a6803649927a62c91a29e6e11750fcd24604
codesQL scan update
Described above

fix: fixing codeQL errors

---

package-lock.json

**Fixes:** 
source: https://github.com/IBM/networking-python-sdk/security/dependabot/15
one package needed to be updated to the latest. 
updated semver package version

fix: updating semver verion to the latest

---

package-lock.json

**Fixes:** Fixes semver package vulnerability 
oudated package version.

chore: updated dependency versions

---

package-lock.json

fix: updating semver dependencies

---

package-lock.json

Fixing vulnerability issues by updating the semver version. 
**Fixes:** this PR is fixing the vulnerability issue by simply bumping up the semver version. 

fix: bumping up the semver version

---

.travis.yml

feat: direct link changes build release

---

.github/workflows/codeql.yml

**Fixes:** 
https://github.com/IBM/networking-python-sdk/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BNMFXGC3DZONUXGLTZNVWA/5b869ea5aa9e968c88615657bae5a6803649927a62c91a29e6e11750fcd24604

Create codeql.yml - new

---

.github/workflows/codeql-analysis.yml
.travis.yml
README.md
requirements.txt

**Fixes:** 
and addressed the following issue: https://ibm-cloudplatform.slack.com/archives/C4XC6SWKG/p1717435157502249?thread_ts=1717145561.364639&cid=C4XC6SWKG

Fix CodeQL analysis 

---

ibm_cloud_networking_services/transit_gateway_apis_v1.py
test/unit/test_transit_gateway_apis_v1.py

Regenerated the transit files to introduce Redundant GRE related changes.
Fixes: https://github.ibm.com/CloudBBS/ts-planning/issues/5244

feat: Added the new connection type - Redundant GRE

---

.travis.yml

**Fixes:**  https://app.travis-ci.com/github/IBM/networking-python-sdk/jobs/622928770#L494

fix: another possible fix

---

ibm_cloud_networking_services/zones_v1.py
test/integration/test_zones_v1.py
test/unit/test_zones_v1.py

**Fixes:** (https://github.ibm.com/NetworkTribe/nw-sdk-terraform-planner/issues/408)

feat(CIS): add partial setup zone

---

package-lock.json

fix: updating a vulnerable pakcage to the latest version number

---

.travis.yml

fix: fixing travis failure

---

.github/workflows/codeql-analysis.yml

https://github.com/IBM/networking-python-sdk/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BNMFXGC3DZONUXGLTZNVWA/5b869ea5aa9e968c88615657bae5a6803649927a62c91a29e6e11750fcd24604

fix: fixing codeql error messages

---

.github/workflows/codeql-analysis.yml
.github/workflows/codeql.yml

fix: Create codeql.yml

---

package-lock.json
package.json

The Issue is addressing the following vulnerability
https://github.com/IBM/networking-java-sdk/security/dependabot/24
**Fixes:** package brace-expansion was identified to have a vulnerability. A new patched version was released addressing the very vulnerability, consequently I'm updating the version  2.0.2
Behavior wasn't altered 
Behavior wasn't altered

fix: Addressed brace-expansion dependency security alert
